# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: kaylee.de_soto@cfa.harvard.edu
author_name: Kaylee de Soto
create_example_module: false
custom_install: true
enforce_style:
- pylint
- black
- isort
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: strict
package_name: snapi
project_license: MIT
project_name: snapi
project_organization: VTDA-Group
python_versions:
- '3.9'
- '3.10'
- '3.11'
- '3.12'
